global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: "managed-nfs-storage"

auth:
  username: posml
  password: "posml!23"

executor: KubernetesExecutor

service:
  type: NodePort
  ports:
    http: 8080
  nodePorts:
    http: "30010"

serviceAccount:
  create: true
  name: "posml"
  automountServiceAccountToken: true
  annotations: {}

rbac:
  create: true
  rules:
    - apiGroups: ["*"]
      resources: ["*"]
      verbs: ["*"]

postgresql:
  enabled: true
  auth:
    enablePostgresUser: false
    username: posml
    password: "posml!23"
    database: bitnami_airflow
    existingSecret: ""
  architecture: standalone